### ISSUE TITLE
Amap killing computer

### ISSUE THREAD

**Issue by FedeClaudi** [SainsburyWellcomeCentre/amap-python#11] opened 2019-12-17 18:38 UTC
Hi, 

Running amap sometimes kills my computer (blue screen of death) [on windows]. 
It doesn't seem to be correlated to other stuff running at the same time, but I can't say for sure what the cause is.

I've noticed that the CPU usage goes to 100% even though it's supposed to be using 10/12 cores, so maybe that's the cause. Will try fewer cores in the future.

**Comment by adamltyson** [comment] 2019-12-17 21:35
I haven’t seen this on windows, but my laptop hasn’t been doing anything else while I’ve tested amap. Could you:
A) try reducing the number of cpu cores used with —n-free-cpus
B) send me the log from when it BSOD?

**Comment by adamltyson** [comment] 2019-12-19 12:38
I can't reproduce this issue, but the windows binaries are a different version to the linux.  The tests also fail on windows vs linux, so the software is definitely different.

**Comment by adamltyson** [comment] 2020-01-14 14:35
@FedeClaudi I still haven't been able to replicate this. I wanted to check, are the pixel sizes set correctly? If not, the registration can use far more RAM than it should (#18).

**Comment by FedeClaudi** [comment] 2020-01-14 14:41
Hey, I haven't used amap since, so I don't have any update on this. Pixel sizes were passed with the `-x -y -z` arguments, and as far as I can tell the values should've been correct.

**Comment by adamltyson** [comment] 2020-02-23 10:14
This hasn't happened since for anyone else on windows. Closing for now, but will reopen if I get any more reports.

@FedeClaudi if you want to get this working on your machine we could try:
* Going through the windows logs to see what actually happens before BSOD
* Logging cpu/memory usage
* Changing niftyreg parameters to use less memory/cpu cores
* Compiling niftyreg on your machine.

**Closed by adamltyson** 2020-02-23 10:14 UTC
Labels: bug, help wanted, high priority
